# manage-order: 5000
version: '3.3'
services:
  logs:
    build:
      context:
        .
      args:
        # must match proxy
        LOGIO_RELATIVE_PATH: '/logs'
    environment:
      PROJECT_NAME: test 
    ports:
      - "6688-6689:6688-6689"
    expose:
        - 6689
    volumes:
    #  - rolling_log:/rolling
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    privileged: true
